[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
betting_program = "GzPnt6kHRES8xp4C7HWcf3M1d92je2sM6x27LNgBQijk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init_main_state_test = "yarn run ts-mocha --require tests/init.ts -p ./tsconfig.json -t 1000000 tests/0.init-main-state.spec.ts"
test = "yarn run ts-mocha --require tests/init.ts -p ./tsconfig.json -t 1000000 tests/**/*.ts"
